---
- hosts: localhost
  become: no

  tasks:

  - name: Stop easyTravel processses
    command: sudo sh /opt/easytravel/easytravel-2.0.0-x64/resources/killbackend.sh
    ignore_errors: yes
    delegate_to: easytravel-btic
