---
- hosts: localhost
  become: no

  tasks:

 - name: Stop easyTravel processses
    command: kill $(ps aux | grep 'easytravel.business' | awk '{print $2}')
    ignore_errors: yes
    delegate_to: easytravel-btic
