---
- hosts: localhost
  become: no

  tasks:
 
  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'ServiceNow Incident created -- INC0199991'
        user: '{{ dt_comment_user }}'
        context: 'ServiceNow'
      body_format: json
 
  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'Ansible Play Started ({{ tower_job_id | default("0") }}): {{ awx_template_name }} - Remediation started -- [Ansible Job](http://{{ awx_dns_name }}/#/jobs/playbook/{{ tower_job_id | default("0") }})'
        user: '{{ dt_comment_user }}'
        context: '{{ dt_comment_context }}'
      body_format: json

  - name: Stop easyTravel processses
    command: sudo /usr/bin/pkill -f 'java'
    ignore_errors: no
    delegate_to: easytravel-btic

  - name: Sleep for 8 seconds
    wait_for:
      timeout: 10

  - name: Restart easytravel
    shell: sudo sh /opt/easytravel/easytravel-2.0.0-x64/resources/starteasyTravelAWX.sh
    delegate_to: easytravel-btic

  - name: "wait for easytravel console to come up"
    uri:
      url: "http://localhost:8094/main"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 15
    delay: 10
    delegate_to: easytravel-btic

  - name: Sleep for 15 seconds before refreshing easyTravel
    wait_for:
      timeout: 15
      
  - name: "wait for easytravel portal to come up"
    uri:
      url: "http://localhost:9080/"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 15
    delay: 10
    delegate_to: easytravel-btic

  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'Ansible Play Started ({{ tower_job_id | default("0") }}): {{ awx_template_name }} - Remediation completed successfully -- [Ansible Job](http://{{ awx_dns_name }}/#/jobs/playbook/{{ tower_job_id | default("0") }})'
        user: '{{ dt_comment_user }}'
        context: '{{ dt_comment_context }}'
      body_format: json
    when: result.status == 200

  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'Ansible Play Started ({{ tower_job_id | default("0") }}): {{ awx_template_name }} - Remediation completed unsuccessfully, please resolve manuallys -- [Ansible Job](http://{{ awx_dns_name }}/#/jobs/playbook/{{ tower_job_id | default("0") }})'
        user: '{{ dt_comment_user }}'
        context: '{{ dt_comment_context }}'
      body_format: json
    when: result.status != 200
