---
- hosts: localhost
  become: no

  tasks:
       
  - name: Log lines to MS Teams
    uri:
     url: "https://atos365.webhook.office.com/webhookb2/4385c4af-d5df-4ad1-98e0-728678a902f0@33440fc6-b7c7-412c-bb73-0e70b0198d5a/IncomingWebhook/e121e4ee2aec42339067501a09a5c33b/95c5fa50-73c1-49fc-95f8-2d43d627c22f"
     body: '{"title":"Incident Created","text":"INC0199991<br>Revenue of the EasyTravel website dropped to <b>0%<b> due to technical issues.<br><i>We are currently working on a solution..</i>","themeColor":"EA4300"}'
     body_format: json
     method: POST
    
  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'ServiceNow Incident created -- INC0199991'
        user: '{{ dt_comment_user }}'
        context: 'ServiceNow'
      body_format: json
 
  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'Ansible Play Started ({{ tower_job_id | default("0") }}): {{ awx_template_name }} - Remediation started -- [Ansible Job](http://{{ awx_dns_name }}/#/jobs/playbook/{{ tower_job_id | default("0") }})'
        user: '{{ dt_comment_user }}'
        context: '{{ dt_comment_context }}'
      body_format: json

  - name: Log lines to MS Teams
    uri:
     url: "https://atos365.webhook.office.com/webhookb2/4385c4af-d5df-4ad1-98e0-728678a902f0@33440fc6-b7c7-412c-bb73-0e70b0198d5a/IncomingWebhook/89d03b41e915411ca88d3b1c35a46468/95c5fa50-73c1-49fc-95f8-2d43d627c22f"
     body: '{"title":"AI root cause found","text":"Automatic resolution initialized<b>We hope to have this restored shortly..","themeColor":"EA4300"}'
     body_format: json
     method: POST

  - name: Stop easyTravel processses
    command: sudo /usr/bin/pkill -f 'java'
    ignore_errors: no
    delegate_to: easytravel-btic

  - name: Sleep for 8 seconds
    wait_for:
      timeout: 10

  - name: Restart easytravel
    shell: sudo sh /opt/easytravel/easytravel-2.0.0-x64/resources/starteasyTravelAWX.sh
    delegate_to: easytravel-btic

  - name: "wait for easytravel console to come up"
    uri:
      url: "http://localhost:8094/main"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 15
    delay: 10
    delegate_to: easytravel-btic

  - name: Sleep for 15 seconds before refreshing easyTravel
    wait_for:
      timeout: 15
      
  - name: "wait for easytravel portal to come up"
    uri:
      url: "http://localhost:9080/"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 15
    delay: 10
    delegate_to: easytravel-btic

  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'Ansible Play Started ({{ tower_job_id | default("0") }}): {{ awx_template_name }} - Remediation completed successfully -- [Ansible Job](http://{{ awx_dns_name }}/#/jobs/playbook/{{ tower_job_id | default("0") }})'
        user: '{{ dt_comment_user }}'
        context: '{{ dt_comment_context }}'
      body_format: json
    when: result.status == 200
    
  - name: Log lines to MS Teams
    uri:
     url: "https://atos365.webhook.office.com/webhookb2/4385c4af-d5df-4ad1-98e0-728678a902f0@33440fc6-b7c7-412c-bb73-0e70b0198d5a/IncomingWebhook/89d03b41e915411ca88d3b1c35a46468/95c5fa50-73c1-49fc-95f8-2d43d627c22f"
     body: '{"title":"INC0199991 automatically mitigated.","text":"All services are running properly. <br><i> Navigate to https://easytravel1.demo.dpm.atos.net/</i> ","themeColor":"EA4300"}'
     body_format: json
     method: POST

  - name: 'push comment to dynatrace'
    uri:
      url: "{{ dynatrace_environment_url }}{{ dt_comments_api }}{{ dt_pid }}/comments"
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "application/json"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body:
        comment: 'Ansible Play Started ({{ tower_job_id | default("0") }}): {{ awx_template_name }} - Remediation completed unsuccessfully, please resolve manuallys -- [Ansible Job](http://{{ awx_dns_name }}/#/jobs/playbook/{{ tower_job_id | default("0") }})'
        user: '{{ dt_comment_user }}'
        context: '{{ dt_comment_context }}'
      body_format: json
    when: result.status != 200
